"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(1, 4);
var mySecondPoint = new point_1.Point(3, 0);
var mythirdPoint = new point_1.Point(2, 9);
var myfourthPoint = new point_1.Point(8, 9);
var arrPoint = [mythirdPoint, myfourthPoint, mySecondPoint];
// console.log(myPoint.toString());
// console.log(myPoint.getX());
// console.log(myPoint.getY());
// myPoint.setX(2);
// myPoint.setY(3);
// console.log(myPoint.toString());
// console.log(myPoint.distanceTolOrigin());
// console.log(myPoint.calculateDistance(mySecondPoint));
// console.log(mySecondPoint.calcularQuadrant());
// console.log(myPoint.calcularQuadrant());
console.log(myPoint.calculateNearest(arrPoint));
